### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by vishalcnz** [relatedcode/GraphQLite#320]
Hello

I am getting Fatal Error when i try to initServer. Can someone help here.

GraphQLite/GQLDate.swift:105: Fatal error
2022-03-25 16:48:43.551683+1300 app[13135:113771] GraphQLite/GQLDate.swift:105: Fatal error

**Comment by relatedcode** [comment]
@vishalcnz Please update to version 1.2.1

**Comment by vishalcnz** [comment]
@relatedcode this is happing again in version 1.2.1
